Add product database
phillipwright7/pivottechschool pull request #7
Opened 2022-11-15 20:39 UTC by phillipwright7

## Summary

Seeding a Database

## Description

This pull request attempts to seed a database from the `products.json` file from our original product server assignment. I am currently at a roadblock with how to troubleshoot the `spew.Dump()` output. Any help is appreciated.

##Output

```
(*sql.Rows)(0xc00010e600)({
 dc: (*sql.driverConn)(0xc0000e81b0)({
  db: (*sql.DB)(0xc00009e750)({
   waitDuration: (int64) 0,
   connector: (sql.dsnConnector) {
    dsn: (string) (len=11) "products.db",
    driver: (*sqlite3.SQLiteDriver)(0xc0000c00c0)({
     Extensions: ([]string) <nil>,
     ConnectHook: (func(*sqlite3.SQLiteConn) error) <nil>
    })
   },
   numClosed: (uint64) 0,
   mu: (sync.Mutex) {
    state: (int32) 0,
    sema: (uint32) 0
   },
   freeConn: ([]*sql.driverConn) (len=1 cap=1) {
    (*sql.driverConn)(0xc0000e81b0)(<already shown>)
   },
   connRequests: (map[uint64]chan sql.connRequest) {
   },
   nextRequest: (uint64) 0,
   numOpen: (int) 2,
   openerCh: (chan struct {}) (cap=1000000) 0xc00008e2a0,
   closed: (bool) false,
   dep: (map[sql.finalCloser]sql.depSet) (len=2) {
    (*sql.driverConn)(0xc0000e8000)({
     db: (*sql.DB)(0xc00009e750)(<already shown>),
     createdAt: (time.Time) 2022-11-15 14:35:53.348652 -0600 CST m=+0.005860310,
     Mutex: (sync.Mutex) {
      state: (int32) 0,
      sema: (uint32) 0
     },
     ci: (*sqlite3.SQLiteConn)(0xc0000ac180)({
      mu: (sync.Mutex) {
       state: (int32) 0,
       sema: (uint32) 0
      },
      db: (*sqlite3._Ctype_struct_sqlite3)(0x100605a30)(panic: bad indir

goroutine 1 [running]:
reflect.packEface({0x1002a2a00?, 0x100605a30?, 0xc000115cb8?})
        /usr/local/go/src/reflect/value.go:115 +0xb2
reflect.valueInterface({0x1002a2a00?, 0x100605a30?, 0x0?}, 0x8?)
        /usr/local/go/src/reflect/value.go:1508 +0xbb
reflect.Value.Interface(...)
        /usr/local/go/src/reflect/value.go:1478
github.com/davecgh/go-spew/spew.handleMethods(0x10040fdc0, {0x10030f140, 0xc0000aa008}, {0x1002b3d80?, 0x100605a30?, 0x1000754e0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/common.go:114 +0x195
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002b3d80?, 0x100605a30?, 0x1000ba745?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:306 +0x4d9
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000117d60, {0x1002a2a00?, 0xc0000ac188?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:154 +0x60e
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002a2a00?, 0xc0000ac188?, 0x1b?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:262 +0xc45
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002c79e0?, 0xc0000ac180?, 0x1000ba745?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:421 +0xddf
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000117d60, {0x1002d05c0?, 0xc0000ac180?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:154 +0x60e
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002d05c0?, 0xc0000ac180?, 0xc?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:262 +0xc45
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002cc2e0?, 0xc0000e8000?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:421 +0xddf
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000117d60, {0x1002c9f20?, 0xc0000e8000?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:154 +0x60e
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002c9f20?, 0xc0000e8000?, 0x1002b2e80?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:262 +0xc45
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002b2e80?, 0xc00009e7b8?, 0xc?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:391 +0xf3f
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002cdee0?, 0xc00009e750?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:421 +0xddf
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000117d60, {0x1002d08c0?, 0xc0000e81b0?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:154 +0x60e
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc0000c9d60, {0x1002d08c0?, 0xc0000e81b0?, 0xc?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:262 +0xc45
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002cc2e0?, 0xc0000e81b0?, 0xc0000061a0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:421 +0xddf
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000117d60, {0x1002c9f20?, 0xc00010e600?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:154 +0x60e
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc0000c9d60, {0x1002c9f20?, 0xc00010e600?, 0xc?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:262 +0xc45
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000117d60, {0x1002ca420?, 0xc00010e600?, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:421 +0xddf
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000117d60, {0x1002c8c00?, 0xc00010e600?, 0x10041adc0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:154 +0x60e
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc0000c9d60, {0x1002c8c00?, 0xc00010e600?, 0x1000e7346?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:262 +0xc45
github.com/davecgh/go-spew/spew.fdump(0x10040fdc0, {0x10030f140, 0xc0000aa008}, {0xc000117e78?, 0x1, 0x0?})
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:465 +0x185
github.com/davecgh/go-spew/spew.Dump(...)
        /Users/phillipwright/go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/spew/dump.go:508
main.main()
        /Users/phillipwright/go/src/github.com/phillipwright7/pivottechschool/cmd/seeder/main.go:83 +0x937
exit status 2
```

2022-11-18 21:09 UTC, jboursiquot requested changes

2022-11-18 21:09 UTC, jboursiquot commented on cmd/seeder/main.go
> +	var prodPth string
Pick a better name for this.

2022-11-18 21:09 UTC, jboursiquot commented on cmd/seeder/main.go
> +	prod, err := os.ReadFile("../server/products.json")
Why not also parameterize this? You did it for the db file.

2022-11-18 21:09 UTC, jboursiquot commented on cmd/seeder/main.go
> +	spew.Dump(rows)
You're already printing out each row. Remove the dump.

2022-11-18 21:09 UTC, jboursiquot commented on cmd/seeder/main.go
> +	var payload []map[string]interface{}
When you use `interface{}` you lose the benefit of compiler type checks. Create a `Product` type and use that here. You'll need it again for the next part of the assignment anyways.

2022-11-25 22:56 UTC, phillipwright7 commented on cmd/seeder/main.go
> +	if err := tx.Commit(); err != nil {
The `tx.Commit()` function ended up being the primary solution for the roadblock I ran into. Does this function only apply to when you manipulate the data on the database? I noticed a commit wasn't required after my select statement.

2022-11-25 22:58 UTC, phillipwright7 reviewed
I got part 1 figured out. Would love a review before I start working on part 2. I also have a clarifying question below:

https://github.com/phillipwright7/pivottechschool/pull/7/commits/3240f967cb7fb63fc9054c8adf284541005e3270#r1032705558

2022-11-27 19:35 UTC, jboursiquot approved these changes

2022-11-27 19:35 UTC, jboursiquot commented on cmd/seeder/main.go
> +	if err := tx.Commit(); err != nil {
Reading data does not require you to commit anything because you haven't changed anything. Think of it like this, you don't `git commit` a file just because you opened it in your editor, only when you make changes to it.

2022-11-27 19:35 UTC, jboursiquot commented on cmd/seeder/main.go
> +	flag.StringVar(&dbPtr, "d", "products.db", "Flag to find products.db")
Those flags (`-d`, `-j`) could be better named. Nobody will understand or remember what these flags stand for a few weeks from now--not even you. Always think of how you name things and have them be as self-describing as possible where appropriate.

2022-11-27 19:47 UTC, phillipwright7 commented on cmd/seeder/main.go
> +	flag.StringVar(&dbPtr, "d", "products.db", "Flag to find products.db")
What would you recommend? I’m unfamiliar with the most idiomatic approach. I figured `-d` and `-j` would be good to signify a .db file and a .json file respectively.

Should I spell it out to say `-db` and `-json`? That seems like it could be a better approach.

2022-11-29 00:07 UTC, merged