Database-Driven Product Server (Part 2)
phillipwright7/pivottechschool pull request #8
Opened 2022-11-29 22:15 UTC by phillipwright7

# Summary

In this pull request, I've refactored my product server handlers to use the product database I've seeded in part 1.

# Description

This product server database hopefully meets all acceptance criteria, as I've tested the different scenarios laid out by my instructor. It includes the use of the `database/sql` package and will write designated HTTP response codes to the response header given the certain scenarios in question.

## Output

### `GET /products?limit=<numeric>`

`curl -i -X GET http://localhost:8080/products?limit=10
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 29 Nov 2022 22:03:01 GMT
Content-Length: 633

[{"id":1,"name":"Water - San Pellegrino","description":"","price":80},{"id":2,"name":"Cape Capensis - Fillet","description":"","price":53},{"id":3,"name":"Bread - Bistro Sour","description":"","price":22},{"id":4,"name":"Lamb - Shoulder","description":"","price":16},{"id":5,"name":"iPhone 14","description":"","price":799},{"id":6,"name":"Kahlua","description":"","price":82},{"id":7,"name":"Doilies - 5, Paper","description":"","price":3},{"id":8,"name":"Crackers - Graham","description":"","price":28},{"id":9,"name":"Long Island Ice Tea","description":"","price":69},{"id":10,"name":"Pork - Kidney","description":"","price":78}]`

### `GET /products/<id>`

`curl -i -X GET http://localhost:8080/products/99
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 29 Nov 2022 22:10:41 GMT
Content-Length: 76

{"id":99,"name":"Lemonade - Pineapple Passion","description":"","price":20}`

### `POST /products`

`curl -i -X POST http://localhost:8080/products -d '{"name": "Apple", "price": 2}'
HTTP/1.1 201 Created
Content-Type: application/json
Date: Tue, 29 Nov 2022 22:13:12 GMT
Content-Length: 0`

### `PUT /products/<id>`

`curl -i -X PUT http://localhost:8080/products/5 -d '{"name": "iPhone 14", "price": 799}'
HTTP/1.1 201 Created
Content-Type: application/json
Date: Tue, 29 Nov 2022 22:12:04 GMT
Content-Length: 0`

### `DELETE /products/<id>`

`curl -i -X DELETE http://localhost:8080/products/100
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 29 Nov 2022 22:15:01 GMT
Content-Length: 0`

2022-11-29 23:58 UTC, jboursiquot requested changes

2022-11-29 23:58 UTC, jboursiquot commented on cmd/server/main.go
> +	rows, err := database.Query("SELECT id, name, price FROM products ORDER BY id LIMIT " + params[0])
Don't do that. You're inviting a SQL injection attack. Use the parameterized query syntax. In addition, you need to validate that limit is indeed a number else your SQL syntax could be invalid if non-numeric value is used for the LIMIT clause.

2022-11-29 23:58 UTC, jboursiquot commented on cmd/server/main.go
> +	rows, err := database.Query("SELECT id, name, price FROM products WHERE id = " + vars["id"])
Same problem here. SQL injection risk.

2022-11-30 15:34 UTC, phillipwright7 reviewed
I've fixed the areas you pointed out, and I've also included my updated output in the PR's comment.

2022-12-07 18:52 UTC, jboursiquot requested changes

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +			log.Fatal(err)
Don't crash your own server

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		log.Fatal(err)
Don't crash your server

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +	rows, err := database.Query("SELECT id, name, price FROM products WHERE id = ?", vars["id"])
Use `QueryRow`

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +	for rows.Next() {
No need for loop if you use `QueryRow`

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +	if payload.ID == 0 {
Use  the QueryRow's returned Row's Scan to check if you get a ErrNoRows to help with this decision instead.

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		log.Fatal(err)
Don't crash

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +	if p.Name == "" || p.Price == 0 {
Put these in a `validate` method on `Product`

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 might be best here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
>  	}
Perform a lookup of the product to be updated earlier in the handler.

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
> +		w.WriteHeader(400)
500 here

2022-12-07 18:52 UTC, jboursiquot commented on cmd/server/main.go
>  	}
Not necessary. If you want to check the prod exists before deleting, do so earlier in the handler

2022-12-08 00:07 UTC, jboursiquot approved these changes

2022-12-08 14:28 UTC, merged