Add CI
phillipwright7/pivottechschool pull request #9
Opened 2022-11-30 15:58 UTC by phillipwright7

## Summary

Adding continuous integration to my calculator project.

## Description

This PR is designed to add CI to my calculator project in order to continuously execute and test with my `calculator_test.go` file.

2022-12-02 00:01 UTC, jboursiquot requested changes
You have a conflict.

2022-12-02 15:19 UTC, phillipwright7 commented
Conflict fixed.

2022-12-03 21:29 UTC, jboursiquot requested changes

2022-12-03 21:29 UTC, jboursiquot commented on Makefile
> +	go build -v ./...
Why the `-v ./...` here. Not needed. Also, you'll want to combine those two commands on one line.

2022-12-03 21:29 UTC, jboursiquot commented on Makefile
> +	cd calculator
Combine those two commands on one line. Also, you already have a `run-seeder` Make target. No need to repeat that here again.

2022-12-03 22:58 UTC, jboursiquot approved these changes

2022-12-04 04:47 UTC, merged